---
name: QMK Firmware Compilation

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'main'
      keymap:
        description: 'Keymap to use'
        required: false
        default: 'josh'
      keyboard:
        description: 'Keyboard to use'
        required: false
        default: 'fingerpunch/sweeeeep'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install QMK CLI
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install qmk

      - name: Compile QMK firmware
        run: |
          qmk setup -y
          qmk compile -e TARGET={{ github.event.inputs.branch || github.ref.name }}-{{ github.event.inputs.keymap }} \
                      -km {{ github.events.inputs.keymap }} \
                      -kb {{ github.events.inputs.keyboard }}

      - name: Upload UF2 artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware-${{ github.event.inputs.branch || github.ref_name }}-${{ github.events.inputs.keymap }}
          path: "*.uf2"
